### ISSUE TITLE
OSM Keys not rendering properly

### ISSUE THREAD

**Issue by binduwavell** [captdeaf/keybard#10]
I have OSM GUI, Alt, Control, Shift on left hand south keys and they are working, however they are not rendering correctly at the moment.

![image](https://github.com/user-attachments/assets/9ec1d134-1934-4af2-8c8b-2d8ace86cd62)

**Comment by captdeaf** [comment]
Does this look correct?
![Screenshot from 2024-09-23 16-05-01](https://github.com/user-attachments/assets/6a6e9ad1-c027-42e4-835e-6a51445ede3f)
