### ISSUE TITLE
Dialogs not blocking clicks/interactions with things "behind" the dialog

### ISSUE THREAD

**Issue by binduwavell** [captdeaf/keybard#13]
Dialog should probably block mouse events on things "behind" the dialog.

![image](https://github.com/user-attachments/assets/03cd7d03-68cf-4654-a2cf-11859e9f934a)

**Comment by binduwavell** [comment]
This is not fixed, at least using an older .kbi file from home.

**Comment by captdeaf** [comment]
Adjusted timeout. (Menu is pure CSS, I'm "closing" it by removing the classes that have :hover, then adding again. May be too quick for some browsers or rendering.) Changes up on https://captdeaf.github.io/keybard/

**Comment by binduwavell** [comment]
I renamed this. You can click the Keyboard Map, Combos and Key Overides buttons while a dialog (tested with QMK Settings) is visible.

**Comment by binduwavell** [comment]
This is working better now. However, the QWERTY, International, etc buttons at the bottom of the screen are still selectable.

**Comment by captdeaf** [comment]
Bleh, fixed that.
