### ISSUE TITLE
Allow selection of repeat key for a layout

### ISSUE THREAD

**Issue by binduwavell** [captdeaf/keybard#16]
They key had a pretty label when assigned, but there does not be a way to assign it using any of the sample boards on the bottom of the screen or by typing the hex code for the key.

**Comment by captdeaf** [comment]
I'll be adding a way to enter custom key strings and hex codes in a bit. Meantime for repeat, how does this look?
![Screenshot from 2024-09-24 13-55-15](https://github.com/user-attachments/assets/306301bc-df5c-4d31-a656-eef1d0fb5555)

**Comment by binduwavell** [comment]
I assigned the Repeat/Again key to my board and using the key does not repeat the last keypress. I reassigned to 0x7c79 and it started working again.

**Comment by captdeaf** [comment]
This is odd, there's 3 repeat keys:

0x0079: KC_REPEAT
0x7c79: QK_REPEAT_KEY
0x7c7a: QK_ALT_REPEAT_KEY

Digging into qmk to figure out what KC_REPEAT_KEY does.

**Comment by captdeaf** [comment]
Got it. KC_REPEAT / KC_AGAIN is "REDO". I've renamed them to KC_REDO, so entering KC_AGAIN will see KC_REDO instead. Also updated the key in the sample board to be QK_REPEAT_KEY

**Comment by binduwavell** [comment]
Working great, thank you!
