### ISSUE TITLE
Feature request: pretty print json output

### ISSUE THREAD

**Issue by jgarvin** [captdeaf/keybard#17]
Both vial and keybard write out *.vil files as one long line, which is harder to debug and makes diffs in version control unreadable (I like to keep all my configs in git). Writing it out with newlines between fields and real indentation for nested objects would help. Python's json module has the indent=True option for this, guessing there must be something similar for JS.

**Comment by captdeaf** [comment]
Completed, please check that it's to your satisfaction?

**Comment by jgarvin** [comment]
:+1:
