### ISSUE TITLE
Loading KeyBard and only thing displayed is MENU

### ISSUE THREAD

**Issue by binduwavell** [captdeaf/keybard#4]
Nothing on the page is interactive. Reload, force reload and clear site cach do not resolve the issue. Clearing site data and reloading does fix the issue.

![image](https://github.com/user-attachments/assets/9211ea34-74bc-48e5-a6d6-76a32e4fcccc)

I found the following steps reliably reproduce the issue:

1. Load KeyBard and connect to Svalboard
2. Select Pre-made layers > Svalboard > QWERTY
3. Reload page and connect to Svalboard

In the event this is tied to my layout, let me know and I'll provide a .kbi file.

**Comment by binduwavell** [comment]
These steps no longer reproduce the issue. Should we close this or leave open for a bit to see if it shows up again?

**Comment by captdeaf** [comment]
For future readers: One cause of this appears to be WebHID getting into a weirdly stuck state.

Try these steps:

1) Close the tab and reopen it.
2) Disconnect the sval for a few seconds before reconnecting.

**Comment by binduwavell** [comment]
Marking closed as I can't reproduce with the steps I listed above. I will either reopen or make a new ticket if this happens again.
