### ISSUE TITLE
The Applied Mods bar in the Keyboard Map is confusing

### ISSUE THREAD

**Issue by binduwavell** [captdeaf/keybard#5]
With an empty key selected in the keymap, I would expect nothing to happen when I select an Applied Mod such as Control. WORKING

With an empty key selected in the keymap and an Applied Mod selected, if I select an eligible key such as C I would expect Control C to be assigned to my keymap. NOT WORKING

When a key is selected that has mods, I would expect the Applied Mods to reflect the selected key. If I change the Applied Mods, I would expect the key on the keymap to be updated. NOT WORKING

**Comment by binduwavell** [comment]
The second expectation appears to be WORKING now

**Comment by captdeaf** [comment]
I see what you mean by #3, but it's expected behavior. Any idea on how to change the wording or display to make people not expect #3?

To meet expectations, it would basically break serial assign without some weird logic, I think.

**Comment by binduwavell** [comment]
Possibly rename it Mods to be applied?

**Comment by captdeaf** [comment]
Done.
