### ISSUE TITLE
Two issues with Print Layer Map

### ISSUE THREAD

**Issue by binduwavell** [captdeaf/keybard#6]
In the following screenshot you can see:

1. The top keys in the keymap overlaying the Layer 0 - default title.
2. Only the first layer is rendered, I have mappings on layers 0 through 5.

![image](https://github.com/user-attachments/assets/98bbb5fa-2cfa-47f4-b433-69153b8a277e)

**Comment by captdeaf** [comment]
🤦 I forgot to git add a file.

**Comment by binduwavell** [comment]
Looks great now, thank you!
