### ISSUE TITLE
Square brackets issue in QWERTY key picker

### ISSUE THREAD

**Issue by stefior** [captdeaf/keybard#8]
Applying the Shift modifier in the QWERTY key picker doesn't show the [ and ] keys, instead showing { and { in the preview.
![image](https://github.com/user-attachments/assets/0aee160c-eaff-434e-bef0-20f9c72602da)

When I try to add shift and one of the [] keys, it then changes it to "LALT(KC_RBRACKET): KC_RBRACKET", but it should be LSFT instead of LALT.
![image](https://github.com/user-attachments/assets/6d984bf5-65d4-4474-ad92-2a4b756e972c)

**Comment by stefior** [comment]
I just realized that [ and ] are normally on the base layer for qwerty and you press shift with them to get { and }, but the issue still stands because it doesn't show the square brackets either way, and the alt instead of shift is the same.

**Comment by captdeaf** [comment]
Thanks, I think I found the issue, and got a fix up.

https://captdeaf.github.io/keybard/ (It's not up at https://keybard.svalboard.app/ )

Can you verify and close if it's fixed for you, too?

Thanks!

**Comment by stefior** [comment]
Yes, it's working for me now. Thank you for the quick response 😃
